# Generated by Django 6.1.1 on 2026-09-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_workitem_descr_to_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Progress'},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_progress_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_progress_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
