# Generated by Django 6.1.1 on 2026-09-23 09:44

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_update_project_statuses'),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('planned', 'Planned'), ('step completed', 'Step Completed'), ('blocked', 'Blocked'), ('awaiting review', 'Awaiting Review'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='step completed', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedded_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tracker.workitem')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='work_item_vec_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
