# Generated by Django 6.1.1 on 2026-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_incident_incidentembedding_monitoringlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in progress', 'In Progress'), ('done', 'Done')], default='planned', max_length=30),
        ),
        migrations.AddField(
            model_name='sprint',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in progress', 'In Progress'), ('done', 'Done')], default='planned', max_length=30),
        ),
    ]
