# Generated by Django 6.1.1 on 2026-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_release_done_at_release_status_sprint_done_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_user_support_number',
            field=models.PositiveIntegerField(default=0, help_text='Counter for sequential user support keys within this project'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='is_support',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this item is a User Support ticket (<PROJECT>-SUP-<ID>)'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
