# Generated by Django 6.1.1 on 2026-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_project_last_user_support_number_workitem_is_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='agent_id',
            field=models.CharField(blank=True, default='', help_text='Agent/model/session identification (e.g. <agent>/<model>/<session-id>) filled out by the LLM', max_length=255),
        ),
        migrations.RenameField(
            model_name='monitoringlog',
            old_name='who_are_you',
            new_name='agent_id',
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='agent_id',
            field=models.CharField(blank=True, default='', help_text='Agent/model/session identification (e.g. <agent>/<model>/<session-id>) filled out by the LLM', max_length=255),
        ),
    ]
