# Generated by Django 6.1.1 on 2026-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_progress_agent_id_monitoringlog_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='hostname',
            field=models.CharField(blank=True, default='', help_text='Optional hostname of the machine/environment where the progress was logged', max_length=255),
        ),
    ]
