name: Deploy to Droplet

on:
  workflow_dispatch:
    # push:
    #   branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Create Ansible vault password file
      run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt
